mmorpg_board/board/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "board"

urlpatterns = [
    # посты
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/add/", views.PostCreateView.as_view(), name="post_add"),

    # отклики
    path("replies/", views.RepliesView.as_view(), name="replies"),
    path('comment/<int:comment_id>/confirm/', views.confirm_comment, name='confirm_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    
    # регистрация и одноразовый код
    path("register/", views.register_view, name="register"),
    path("login-with-code/<int:user_id>/", views.login_with_code_view, name="login_with_code"),
    path("login/", auth_views.LoginView.as_view(template_name="board/login.html"), name="login"),
    path("logout/", views.logout_view, name="logout_view"),
]

mmorpg_board/mmorpg_board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from ckeditor_uploader.views import upload, browse
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^upload/', login_required(upload), name='ckeditor_upload'),
    re_path(r'^browse/', login_required(never_cache(browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg_board/board/models.py
from datetime import timedelta
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField 
from django.conf import settings
from django.utils import timezone
import secrets
import string
from django.contrib.auth.models import AbstractUser


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at']),
        ]


class Reply(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_replies')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_replies')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_accepted = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_at']


class CustomUser(AbstractUser):
    is_verified = models.BooleanField(default=False)
    confirmation_token = models.CharField(max_length=6, blank=True, null=True)
    token_created_at = models.DateTimeField(auto_now_add=True)

    def generate_confirmation_token(self):
        alphabet = string.digits
        self.confirmation_token = ''.join(secrets.choice(alphabet) for _ in range(6))
        self.token_created_at = timezone.now()
        self.save()

    def is_token_valid(self):
        return self.token_created_at >= timezone.now() - timedelta(minutes=2)

    def clear_confirmation_token(self):
        self.confirmation_token = None
        self.save()

mmorpg_board/board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Reply, CustomUser
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Post
        fields = ['category', 'title', 'content']


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4, 'cols': 75}),
        }
        labels = {
            'content': '',
        }


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email, is_verified=True).exists():
            raise forms.ValidationError("Пользователь с этим e-mail уже зарегистрирован и подтверждён.")
        return email


class CodeVerificationForm(forms.Form):
    code = forms.CharField(max_length=6, required=True, widget=forms.TextInput(attrs={'placeholder': 'Введите код'}))

    def clean_code(self):
        code = self.cleaned_data['code']
        if not code.isdigit() or len(code) != 6:
            raise forms.ValidationError("Код должен состоять из 6 цифр.")
        return code

mmorpg_board/board/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail
from django.urls import reverse_lazy

from board.filters import ReplyFilter

from .models import CustomUser, Post, Reply
from .forms import PostForm, RegistrationForm, CodeVerificationForm, ReplyForm


@login_required
def logout_view(request):
    logout(request)
    return redirect("board:post_list")

# -------------------------------------------------
# Посты
# -------------------------------------------------

class PostListView(ListView):
    model = Post
    template_name = "board/post_list.html"
    context_object_name = "posts"
    paginate_by = 10


class PostDetailView(DetailView):
    model = Post
    template_name = "board/actions/post_detail.html"
    context_object_name = "post"

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = ReplyForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            send_mail(
                subject='На ваш пост был оставлен комментарий!',
                message=(
                    f'Привет, '
                    f'{post.user.username}!\n'
                    f'На ваше объявление "{post.title}" '
                    f'был оставлен комментарий от пользователя '
                    f'{comment.user.username} '
                    f'с содержанием:\n"{comment.content}"'
                ),
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[post.user.email]
            )
            return redirect('board:post_detail', pk=post.pk)
        return render(request, 'board:post_detail.html', {'form': form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReplyForm()
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "board/actions/post_add.html"
    success_url = reverse_lazy("board:post_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

# -------------------------------------------------
# Отклики
# -------------------------------------------------

class RepliesView(LoginRequiredMixin, ListView):

    def __init__(self):
        super().__init__()
        self.filter = None

    model = Reply
    context_object_name = 'comments'
    template_name = 'board/actions/replies.html'
    filterset_class = ReplyFilter

    def get_queryset(self):
        base_qs = super().get_queryset()
        qs = base_qs.filter(post__user=self.request.user)
        self.filter = ReplyFilter(self.request.GET, queryset=qs, request=self.request.user)
        return self.filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filter
        return context


def confirm_comment(request, comment_id):
    comment = Reply.objects.get(id=comment_id)
    comment.is_accepted = True
    comment.save()
    send_mail(
        subject='Ваш отклик одобрен',
        message=f'Привет, {comment.user.username}! Комментарий, который вы оставили, был одобрен автором объявления!',
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[comment.user.email]
    )
    return redirect('board:replies')


def delete_comment(request, comment_id):
    Reply.objects.get(id=comment_id).delete()
    return redirect('board:replies')

# -------------------------------------------------
# генерация кода / регистрация
# -------------------------------------------------

def register_view(request):  
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if CustomUser.objects.filter(email=email, is_verified=True).exists():
                messages.error(request, "Пользователь с этим e-mail уже зарегистрирован и подтверждён.")
                return redirect('board:login')
            
            user = form.save(commit=False)
            user.is_active = True
            user.is_verified = False
            user.save()

            user.generate_confirmation_token()
            send_mail(
                subject="Код подтверждения регистрации",
                message=f"Ваш код подтверждения: {user.confirmation_token}",
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[user.email],
            )

            messages.success(request, "Регистрация успешна! На вашу почту отправлен код для подтверждения.")
            return redirect('board:login_with_code', user_id=user.id)

    else:
        form = RegistrationForm()
    return render(request, 'board/register.html', {'form': form})


def login_with_code_view(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)

    if request.method == "POST":
        form = CodeVerificationForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            if user.confirmation_token == code and user.is_token_valid():
                user.is_verified = True
                user.confirmation_token = None
                user.save()

                login(request, user)

                messages.success(request, "Регистрация подтверждена! Вы успешно вошли на сайт.")
                return redirect('board:post_list')
            else:
                messages.error(request, "Неверный или просроченный код.")
    else:
        form = CodeVerificationForm()
    
    return render(request, 'board/login_with_code.html', {'form': form})

mmorpg_board/board/templates/board/actions/post_add.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% if object %}Редактировать{% else %}Создать{% endif %} объявление</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>

  {{ form.media }}
{% endblock %}

mmorpg_board/board/templates/board/actions/post_detail.html
<!-- детали поста и отклика -->
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="card mb-4">
  <div class="card-body">
    <h2 class="card-title">{{ post.title }}</h2>
    <p class="text-muted mb-1">
      <strong>Категория:</strong> {{ post.category.name }} |
      <strong>Автор:</strong> {{ post.user.username }}
    </p>

    <div class="post-content-wrapper">
      {{ post.content|safe }}
    </div>

    <hr>
    <br>
    {% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
    {% else %}
        <h5>Авторизуйтесь, чтобы оставлять комментарии</h5>
    {% endif %}

    {% if post.post_replies.all %}
         <h3>Все комментарии</h3>
        {% for comment in post.post_replies.all %}
            <p class="text-muted mb-1">{{ comment.user.username }} от {{ comment.created_at }}:</p>
             {{ comment.content }}
        {% endfor %}
    {% else %}
         <br>
         <h5>Комментариев пока нет!</h5>
    {% endif %}

{% endblock content %}

mmorpg_board/board/templates/board/actions/replies.html
{% extends "base.html" %}

{% block title %}Все отклики{% endblock title %}

{% block content %}
<h4>Все отклики</h4>
<form action="" method="get" class="mb-3">
    <div class="d-flex justify-content-center align-items-start flex-column" style="width: max-content; margin: 0 auto;">
        {{ filter.form }}
        <input class="btn btn-primary btn-sm mt-2" type="submit" value="Применить">
    </div>
</form>


{% if comments %}
    {% for comment in comments %}
        <div class="card mb-2 mx-auto" style="max-width: 600px;">
            <div class="card-body d-flex justify-content-between align-items-start">

                <div>
                    <p class="mb-1"><strong>{{ comment.user.username }}</strong>:</p>
                    <p class="mb-0">{{ comment.content }}</p>
                </div>

                {% if not comment.is_accepted %}
                    <div class="d-flex flex-column ms-3">
                        <a class="btn btn-success btn-sm mb-1" href="{% url 'board:confirm_comment' comment.id %}">Принять</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'board:delete_comment' comment.id %}">Удалить</a>
                    </div>
                {% else %}
                    <div class="ms-3">
                        <small class="text-muted">Статус: Принят</small>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <h5 class="text-center mt-4">Нет откликов!</h5>
{% endif %}
{% endblock content %}