mmorpg_board/board/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "board"

urlpatterns = [
    # посты
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/add/", views.PostCreateView.as_view(), name="post_add"),

    # отклики
    path("replies/", views.RepliesView.as_view(), name="replies"),
    path('comment/<int:comment_id>/confirm/', views.confirm_comment, name='confirm_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    
    # регистрация и одноразовый код
    path("register/", views.register_view, name="register"),
    path("login-with-code/<int:user_id>/", views.login_with_code_view, name="login_with_code"),
    path("login/", auth_views.LoginView.as_view(template_name="board/login.html"), name="login"),
    path("logout/", views.logout_view, name="logout_view"),
]

mmorpg_board/mmorpg_board/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from ckeditor_uploader.views import upload, browse
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^upload/', login_required(upload), name='ckeditor_upload'),
    re_path(r'^browse/', login_required(never_cache(browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg_board/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}MMORPG Board{% endblock %}</title>
    <!-- Bootstrap CSS (CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container">
        <a class="navbar-brand" href="{% url 'board:post_list' %}">MMO-board</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ms-auto align-items-center">
            {% if user.is_authenticated %}
              <li class="nav-item"><span class="navbar-text me-5">{{ user.username }}</span></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'board:post_add' %}">Создать</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'board:replies' %}">Отклики</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'board:logout_view' %}">Выйти</a></li>
            {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'board:register' %}">Регистрация</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'board:login' %}">Войти</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <main class="container">
      {% block content %}{% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>